config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from post.views import home_view


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', home_view, name='home_view'),
    path('posts/', include('post.urls', namespace='post')),
    path('user/', include('user.urls', namespace='user') ),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.contrib import admin
from django.urls import path
from post.views import  myposts_view , add_post , post_detail , post_update , delete

app_name ='post'

urlpatterns = [
    path('myposts/' , myposts_view, name='myposts_view' ),
    path('add-post/' , add_post, name='add_post' ),
    path('myposts/<int:id>' , post_detail, name='post_detail' ),
    path('myposts/<int:id>/update' , post_update, name='post_update' ),
    path('myposts/<int:id>/delete' , delete, name='delete' ),
   
]

user/urls.py
from django.contrib import admin
from django.urls import path
from .views import register, login_view, logout_view

app_name = 'user'

urlpatterns =[
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),

]

post/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse



class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE )
    title = models.CharField(max_length=200)
    content = models.TextField()
    picture = models.FileField(blank=True , null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_deleted = models.BooleanField(default=False)

    def delete_from_page(self):

        self.is_deleted = not self.is_deleted
        self.save()

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
    
      return reverse("post_detail", kwargs={ "id" : self.pk } )
    

user/models.py
from django.db import models

# Create your models here.

post/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','content','picture']

user/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label = "Kimsin")
    password = forms.CharField(label = "Parolan",widget = forms.PasswordInput)

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50 , label= 'Kimsin')
    password = forms.CharField(max_length=50 , label= 'Parolan', widget= forms.PasswordInput)
    confirm = forms.CharField(max_length=50 , label= 'Bi Daha', widget= forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        confirm = self.cleaned_data.get('confirm')

        if password and confirm and password != confirm:
            raise forms.ValidationError('Aynı parolayı gir lütfen')
        
        values = {
            'username' : username,
            'password' : password
        }

        return values

post/views.py
from django.shortcuts import render , redirect 
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import get_object_or_404
from .models import Post
from .forms import PostForm



def home_view(request):
    posts = Post.objects.filter(is_deleted=False) #order_by kullanilabilir
    context = dict(
        posts = posts
    )

    return render(request, 'home_page.html', context)

@login_required(login_url="/user/login")
def myposts_view(request):
    posts = Post.objects.filter(is_deleted= False, user= request.user)

    context = dict(
        posts =posts
    )

    return render(request, 'post/myposts.html', context)

@login_required(login_url="/user/login")
def add_post(request):
    form = PostForm(request.POST or None, request.FILES or None)
    
    if form.is_valid():
        post = form.save(commit = False)
        post.user = request.user
        post.save()

        messages.success(request, 'Bravo Post Ekledin!')
        return redirect('/')
    context = {
        'form': form
    }
    return render(request, 'post/add_post.html', context)

def post_detail(request  , id): 
    item = get_object_or_404(Post, pk = id )
    context = dict(
        item = item,
        is_editable = True if item.user == request.user else False
    )
    return render(request, 'post/post_detail.html' , context)

@login_required(login_url="/user/login")
def post_update(request, id):

    post  = get_object_or_404(Post, id=id )
    form = PostForm(request.POST or None , request.FILES or None, instance = post)
     
    if form.is_valid():
        post = form.save(commit = False)
        post.user = request.user
        post.save()

        messages.success(request, 'Bravo Postunu Düzenledin!')
        return redirect('post:myposts_view')

    context = dict(
        form = form ,
    )

    return render(request, 'post/post_update.html', context)

@login_required(login_url="/user/login")
def delete(request,  id):
    post = get_object_or_404(Post, id=id)

    post.delete_from_page()
    return redirect('/')

user/views.py
from django.contrib import messages
from django.contrib.auth import login , authenticate , logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_protect
from .forms import RegisterForm , LoginForm

@csrf_protect
def register(request):
    
    if request.user.is_authenticated :
            messages.info(request, 'Zaten bir hesapla giriş yaptın!')
            return redirect('/')
    form = RegisterForm(request.POST or None)

    if form.is_valid():
        username =  form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')


        newUser = User(username = username)
        if User.objects.filter(username = username).first():
            messages.info(request, "Bu kullanıcı adı daha önce alındı")
            return redirect('user:register')
    
        newUser.set_password(password)

        newUser.save()
        login(request, newUser)
        messages.info(request, 'Bravo kaydoldun!')
        return redirect('/')
    
    
    
    context = {
        'form' : form
    }
    
    return render(request, 'interface/register.html', context)

@csrf_protect
def login_view(request):

    if request.user.is_authenticated :
            messages.info(request, 'Zaten girdin')
            return redirect('/')
    form = LoginForm(request.POST or None)

    context = {
        'form' : form
    }
    
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username,password = password)
        if user is None:
            messages.info(request,'Kullanici ismi veya parola yanlis')
            return render(request, 'interface/login.html',context)
        
        messages.success(request, 'Aferin giris yaptin')
        login(request, user)
        return redirect('/')
       
    return render(request, 'interface/login.html', context)
    
    
@csrf_protect
def logout_view(request):
    logout(request)
    messages.success(request,"Çıkış Yapıldı")
    return redirect('/')

post/templates/allposts.html
{% extends 'base/main.html' %}

{% block container %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<h1>Ana Sayfa</h1>
<div class="section_our_solution">
  <div class="row"> 
    {% for post in posts %}
    <div class="col-4" >
        
        <div class="solution_cards_box"  >
         
          <div class="solution_card" style="width: 25rem; height: 25rem;">
            
            {% if post.picture %}
            <img class="fit" src="{{post.picture.url}}" alt="yok" >
            {% endif %}
            <div class="solu_title">
              <h3>{{ post.title }}</h3>
            </div>
            <div class="solu_description">
              <p>
                {{ post.content|truncatewords:10 }}
              </p>
              <a href="{% url 'post:read_only' id=post.id %}"><button type="button" class="read_more_btn">Devamı</button></a>
              
            </div>
          </div>
         
        </div>
        
      </div>
    {% endfor %}
  </div>
</div>




{% endblock container %}






<h1 class="text-primary">Ana Sayfa</h1>
<div class="row">
    {% for post in posts %}
    <div class="col-4">
      
      <div class="card ">
        <div class="card-body -cart " style="width: 25rem; height: 25rem;">
          {% if post.picture %}
          <img class="img-fluid rounded - fit" src="{{post.picture.url}}" alt="yok">
          {% endif %}
          <a href="">
                <span><h5  class="card-item" >{{ post.title }}</h5></span>
          </a>
          <p class="card-text">{{ post.content|truncatewords:10 }}</p>
          <hr>
          <p>{{ item.post.user }}</p>
          
        </div>
      </div>
      <hr>
     
    </div>
    {% endfor %}
</div>

post/templates/base/footer.html
{% load static %}

<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="/" class="nav-link px-2 text-body-secondary">Ana Sayfa</a></li>
    </ul>
    <p class="text-center text-body-secondary">© 2023 Company, Inc</p>
  </footer>

<script> src="{% static 'js/bootstrap.bundle.min.js' %}"</script>

post/templates/base/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} PostPod {% endblock title %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    
    <style>
        .fit {
            width: 100%;
            height: 60%;
        }
        .section_our_solution .row {
          align-items: center;
        }
        
        .our_solution_category {
          display: flex;
          flex-direction: row;
          flex-wrap: wrap;
        }
        .our_solution_category .solution_cards_box {
          display: flex;
          flex-direction: column;
          justify-content: center;
        }
        .solution_cards_box .solution_card {
          flex: 0 50%;
          background: #fff;
          box-shadow: 0 2px 4px 0 rgba(136, 144, 195, 0.2),
            0 5px 15px 0 rgba(37, 44, 97, 0.15);
          border-radius: 15px;
          margin: 8px;
          padding: 10px 15px;
          position: relative;
          z-index: 1;
          overflow: hidden;
          min-height: 265px;
          transition: 0.7s;
        }
        
        .solution_cards_box .solution_card:hover {
          background: #309df0;
          color: #fff;
          transform: scale(1.1);
          z-index: 9;
        }
        
        .solution_cards_box .solution_card:hover::before {
          background: rgb(85 108 214 / 10%);
        }
        
        .solution_cards_box .solution_card:hover .solu_title h3,
        .solution_cards_box .solution_card:hover .solu_description p {
          color: #fff;
        }
        
        .solution_cards_box .solution_card:before {
          content: "";
          position: absolute;
          background: rgb(85 108 214 / 5%);
          width: 170px;
          height: 400px;
          z-index: -1;
          transform: rotate(42deg);
          right: -56px;
          top: -23px;
          border-radius: 35px;
        }
        
        .solution_cards_box .solution_card:hover .solu_description button {
          background: #fff !important;
          color: #309df0;
        }
        
        .solution_card .solu_title h3 {
          color: #212121;
          font-size: 1.3rem;
          margin-top: 13px;
          margin-bottom: 13px;
        }
        
        .solution_card .solu_description p {
          font-size: 15px;
          margin-bottom: 15px;
        }
        
        .solution_card .solu_description button {
          border: 0;
          border-radius: 15px;
          background: linear-gradient(
            140deg,
            #42c3ca 0%,
            #42c3ca 50%,
            #42c3cac7 75%
          ) !important;
          color: #fff;
          font-weight: 500;
          font-size: 1rem;
          padding: 5px 16px;
        }
        
        .our_solution_content h1 {
          text-transform: capitalize;
          margin-bottom: 1rem;
          font-size: 2.5rem;
        }
      
        
        .hover_color_bubble {
          position: absolute;
          background: rgb(54 81 207 / 15%);
          width: 100rem;
          height: 100rem;
          left: 0;
          right: 0;
          z-index: -1;
          top: 16rem;
          border-radius: 50%;
          transform: rotate(-36deg);
          left: -18rem;
          transition: 0.7s;
        }
        
        .solution_cards_box .solution_card:hover .hover_color_bubble {
          top: 0rem;
        }
        
        .solution_cards_box .solution_card .so_top_icon {
          width: 60px;
          height: 60px;
          border-radius: 50%;
          background: #fff;
          overflow: hidden;
          display: flex;
          align-items: center;
          justify-content: center;
        }
        
        .solution_cards_box .solution_card .so_top_icon img {
          width: 40px;
          height: 50px;
          object-fit: contain;
        }
        
        /*start media query*/
        @media screen and (min-width: 320px) {
          .sol_card_top_3 {
            position: relative;
            top: 0;
          }
        
          .our_solution_category {
            width: 100%;
            margin: 0 auto;
          }
        
          .our_solution_category .solution_cards_box {
            flex: auto;
          }
        }
        @media only screen and (min-width: 768px) {
          .our_solution_category .solution_cards_box {
            flex: 1;
          }
        }
        @media only screen and (min-width: 1024px) {
          .sol_card_top_3 {
            position: relative;
            top: -3rem;
          }
          .our_solution_category {
            width: 50%;
            margin: 0 auto;
          }
        }
        
    </style>
</head>

post/templates/base/main.html
<!DOCTYPE html>
<html lang="en">

{% include 'base/head.html' %}

<body>

    {% block navbar %}
    {% include 'base/nav.html' %}
    {% endblock navbar %}


    {% if messages %}
                
                    {% for message in messages %}
                    {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                    {% endif %}


                    {% endfor %}
                
                {% endif %}
    
    
   
    
    <div class= "container">
        {% block container %}
        {% endblock container %}
    </div>
    {% block title %}
    {% endblock title %}
    
    

    {% include 'base/footer.html' %}
</body>
</html>

post/templates/base/nav.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-body-tertiary my-3 navbar-dark bg-dark">
 

    <div class="container justify-content-center">
        <div class="collapse navbar-collapse flex-grow-0" id="navbarSupportedContent"> 

            <ol class="nav nav-pills nav-fill">
                <ol class="nav-item">
                  <a class="nav-link active" aria-current="page" href="/">Ana Sayfa</a>
                </ol>
                <ol class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'post:myposts_view' %}">Postlarım</a>
                </ol>
                <ol class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'post:add_post' %}">Post Ekle</a>
                </ol>
                
                {% if request.user.is_authenticated %}
                <ol class="nav-item">
                  <a class="nav-link" aria-current="" href="{% url 'user:logout' %}" >Çıkış Yap</a>
                
                {% else %}
                <ol class="nav-item">
                  <a class="nav-link" aria-current="" href="{% url 'user:login' %}" >Giris Yap</a>
                {% endif %}
                </ol>
                
            </ol>


        </div>
       
    </div>
    
</nav>

post/templates/home_page.html
{% extends 'base/main.html' %}

{% block container %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<h1>Ana Sayfa</h1>
<div class="section_our_solution">
  <div class="row"> 
    {% for post in posts %}
    <div class="col-4" >
        
        <div class="solution_cards_box"  >
         
          <div class="solution_card" style="width: 25rem; height: 25rem;">
            
            {% if post.picture %}
            <img class="fit" src="{{post.picture.url}}" alt="yok" >
            {% endif %}
            <div class="solu_title">
              <h3>{{ post.title }}</h3>
            </div>
            <div class="solu_description">
              <p>
                {{ post.content|truncatewords:10 }}
              </p>
              <a href="{% url 'post:post_detail' id=post.id %}"><button type="button" class="read_more_btn">Devamı</button></a>
              
            </div>
          </div>
         
        </div>
        
      </div>
    {% endfor %}
  </div>
</div>




{% endblock container %}






<h1 class="text-primary">Ana Sayfa</h1>
<div class="row">
    {% for post in posts %}
    <div class="col-4">
      
      <div class="card ">
        <div class="card-body -cart " style="width: 25rem; height: 25rem;">
          {% if post.picture %}
          <img class="img-fluid rounded - fit" src="{{post.picture.url}}" alt="yok">
          {% endif %}
          <a href="">
                <span><h5  class="card-item" >{{ post.title }}</h5></span>
          </a>
          <p class="card-text">{{ post.content|truncatewords:10 }}</p>
          <hr>
          <p>{{ item.post.user }}</p>
          
        </div>
      </div>
      <hr>
     
    </div>
    {% endfor %}
</div>

post/templates/interface/login.html
{% extends 'base/main.html' %}

{% block container %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş Yap</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            
            {{form.as_p}}
            <br>
            <button type = "submit" class = "btn btn-danger">Giriş Yap</button> 
        </form>
        <hr>
        <a class="btn btn-primary active" role="button" aria-disabled="true" href="{% url 'user:register' %}">Hesabiniz Yoksa Kayit Olmak Icin Tiklayin</a>

    
  </div>
  
  </div>
  
{% endblock container %}

post/templates/interface/register.html
{% extends 'base/main.html' %}

{% block container %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt Ol</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            
            {{form.as_p}}
            <br>
            <button type = "submit" class = "btn btn-danger">Kayit Ol</button>
        </form>
        <hr>
        <a class="btn btn-primary active" role="button" aria-disabled="true" href="{% url 'user:login' %}">Hesabiniz Varsa Giris Yapmak Icin Tiklayin</a>

    </div>
  </div>


{% endblock container %}

post/templates/post/add_post.html
{% extends 'base/main.html' %}
{% block container %}


<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Post Oluştur</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data" >
            {% csrf_token %}
            
            {{form.as_p}}
            <br>
            <button type = "submit" class = "btn btn-danger">Post Ekle</button>
        </form>
    </div>
  </div>

{% endblock container %}

post/templates/post/myposts.html
{% extends 'base/main.html' %}
{% load static %}
{% block container %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<h1>Postlarım</h1>
<div class="section_our_solution">
  <div class="row"> 
    {% for post in posts %}
    <div class="col-4" >
        
        <div class="solution_cards_box"  >
         
          <div class="solution_card" style="width: 25rem; height: 25rem;">
            
            {% if post.picture %}
            <img class="fit" src="{{post.picture.url}}" alt="yok" >
            {% endif %}
            <div class="solu_title">
              <h3>{{ post.title }}</h3>
            </div>
            <div class="solu_description">
              <p>
                {{ post.content|truncatewords:10 }}
              </p>
              <a href="{% url 'post:post_detail' id=post.id %}"><button type="button" class="read_more_btn">Devamı</button></a>
              
            </div>
          </div>
         
        </div>
        
      </div>
    {% endfor %}
  </div>
</div>



{% endblock container %}

post/templates/post/post_detail.html
{% extends 'base/main.html' %}

{% block container %}
<div class="row justify-content-center align-items-center">
    <div class="card" style="width: 55rem;">
      <div class="card-body">
        {% if item.picture %}
        <img class="img-fluid rounded" src="{{item.picture.url}}" alt="yok" width="800" >
        {% endif %}
        <hr>
        <h1 class="card-title">{{ item.title }}</h1>
  
        <p class="card-text">{{ item.content }}</p>
        
        {% if is_editable %}
        <a href="{% url 'post:post_update' id=item.id %}" class="btn btn-primary my-3">Duzenle</a>
        <a href="{% url 'post:delete' id=item.id %}" class="btn btn-primary my-3">Sil</a>
        <a href="/" class="btn btn-primary my-3">Geri Don</a> 
        {% endif %}
        <ul class="list-unstyled">
        Oluşturulma Tarihi : {{ item.created_at }}
      </ul>
      </div>
     <h2>{{ is_editable }}</h2>
  </div>
</div>
{% endblock container %}

post/templates/post/post_update.html
{% extends 'base/main.html' %}

{% block container %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Yazi Güncelle</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data" >
            {% csrf_token %}
            
            {{form.as_p}}
            <br>
            <button type = "submit" class = "btn btn-danger">Güncelle</button>
        </form>
    </div>
  </div>

{% endblock container %}